#!/bin/sh

# Startup script for PRISM GUI (Linux/Solaris)

# PRISM home directory
PRISM_DIR="/Applications/prism-4.3.1-osx64"

# Launch using main PRISM script
PRISM_MAINCLASS=userinterface.GUIPrism
PRISM_HEADLESS=false
export PRISM_MAINCLASS PRISM_HEADLESS
$PRISM_DIR/bin/prism "$@"
